sudo: false
language: python
dist: xenial
python:
  - "3.7"

install:
  - pip install tox
  - pip install coveralls

env:
  matrix:
    - TOXENV=django111-py27
    - TOXENV=django2-py27
    - TOXENV=django21-py27
    - TOXENV=pycodestyle-py27
    - TOXENV=django111-py35
    - TOXENV=django2-py35
    - TOXENV=django21-py35
    - TOXENV=django111-py36
    - TOXENV=django2-py36
    - TOXENV=django21-py36
    - TOXENV=django111-py37
    - TOXENV=django2-py37
    - TOXENV=django21-py37
    - TOXENV=pycodestyle-py37

cache: pip

script:
  - tox
  - coveralls
